network:
  version: 2
  wifis:
    wlxbcec43446b2b:
      access-points:
        deco-cpd-x:
          password: fitfab8888
        iPhone:
          password: d5b844519e44666bc253ef364b5465a9e97597e3c6c515e792741a60dd6af62c
        gp6p2:
          password: fitfabtest
      dhcp4: true
      optional: true
  ethernets:
    eth0:
      dhcp4: false
      addresses: [192.168.1.3/24]
      routes:
        - to: 192.168.1.2/32
          via: 192.168.1.3
    enx7cc2c64a19b7:
      dhcp4: false
      addresses: [192.168.1.12/24]
      routes:
        - to: 192.168.1.4/32
          via: 192.168.1.12
